#!/usr/bin/env python3
"""Synchronize user-installed agent skills into this public catalog.

The script intentionally excludes system/plugin caches, dependency trees, VCS data,
credentials, nested skill packages, and generated binaries over 50 MiB. It preserves
distinct project variants and fails closed on possible secrets.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


REPO_ROOT = Path(__file__).resolve().parents[1]
HOME = Path.home()

SOURCE_ROOTS = (
    ("Agents", HOME / ".agents/skills"),
    ("Codex", HOME / ".codex/skills"),
    ("Claude", HOME / ".claude/skills"),
    ("Gemini", HOME / ".gemini/skills"),
    ("Gemini Anti-Gravity", HOME / ".gemini/antigravity/skills"),
    ("Gemini Config", HOME / ".gemini/config/skills"),
    ("Cursor", HOME / ".cursor/skills"),
    ("OpenCode", HOME / ".config/opencode/skills"),
    ("Copilot", HOME / ".copilot/skills"),
    ("Hermes", HOME / ".hermes/skills"),
    ("Hermes Source", HOME / ".hermes/hermes-agent/skills"),
    ("Shared", HOME / "Documents/Developer/_shared/skills"),
    ("Content Repurpose", HOME / "Documents/Samins Video index/ContentRepurposeSystem/skills"),
    ("Testing Claude", HOME / "Documents/Testing software/.claude/skills"),
    ("Testing Codex", HOME / "Documents/Testing software/.codex/skills"),
    ("Video Editor Agents", HOME / "Documents/Video Editor/.agents/skills"),
    ("Video Editor Claude", HOME / "Documents/Video Editor/.claude/skills"),
    ("Video Editor", HOME / "Documents/Video Editor/agent/skills"),
    ("Woterclip", HOME / "Documents/augment-projects/woterclip/skills"),
    ("Evolving Brain", HOME / "Evolving Brain/9 - Operations/skills"),
    ("Evolving Brain Template", HOME / "Evolving-Brain-Template/9 - Operations/skills"),
    ("Alpaca", HOME / "plugins/alpaca/skills"),
    ("Home Skills", HOME / "skills"),
)

SOURCE_PRIORITY = {label: index for index, (label, _) in enumerate(SOURCE_ROOTS)}
EXCLUDED_DIRS = {
    ".git",
    ".system",
    "node_modules",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    ".ruff_cache",
    ".venv",
    "venv",
}
EXCLUDED_FILES = {".DS_Store", "skills.lock.json"}
SECRET_FILE_PATTERNS = (
    re.compile(r"^\.env(?:\..+)?$", re.I),
    re.compile(r"^(?:credentials?|secrets?)(?:\..+)?$", re.I),
    re.compile(r"^(?:id_rsa|id_ed25519)(?:\..+)?$", re.I),
    re.compile(r".*\.(?:pem|p12|pfx|key)$", re.I),
    re.compile(r"^\.(?:npmrc|pypirc)$", re.I),
)
SECRET_CONTENT_PATTERNS = (
    ("private key", re.compile(r"-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----")),
    ("GitHub token", re.compile(r"\bgh[oprsu]_[A-Za-z0-9_]{30,}\b")),
    ("Slack token", re.compile(r"\bxox[baprs]-[A-Za-z0-9-]{20,}\b")),
    ("AWS access key", re.compile(r"\bAKIA[0-9A-Z]{16}\b")),
    ("live Stripe key", re.compile(r"\bsk_live_[A-Za-z0-9]{16,}\b")),
)
MAX_FILE_BYTES = 50 * 1024 * 1024
TEXT_SCAN_BYTES = 2 * 1024 * 1024
GENERATED_README_MARKER = "<!-- generated by scripts/sync_skill_catalog.py -->"


@dataclass(frozen=True)
class SkillCandidate:
    name: str
    description: str
    source: str
    path: Path
    skill_hash: str
    package_files: int
    package_bytes: int
    origin_url: str | None
    needs_normalization: bool


def _unquote(raw: str) -> str:
    raw = raw.strip()
    if len(raw) >= 2 and raw[0] == raw[-1] and raw[0] in {'"', "'"}:
        raw = raw[1:-1]
    return raw.replace("\\\"", '"').strip()


def _frontmatter_value(frontmatter: str, key: str) -> str | None:
    lines = frontmatter.splitlines()
    for index, line in enumerate(lines):
        item = re.match(rf"^{re.escape(key)}:\s*(.*?)\s*$", line)
        if not item:
            continue
        raw = item.group(1)
        if raw not in {"|", ">", "|-", ">-", "|+", ">+"}:
            return _unquote(raw)
        block: list[str] = []
        for next_line in lines[index + 1 :]:
            if next_line and not next_line[0].isspace():
                break
            block.append(next_line.strip())
        separator = "\n" if raw.startswith("|") else " "
        return separator.join(line for line in block if line).strip()
    return None


def _legacy_description(text: str, name: str) -> str:
    for paragraph in re.split(r"\n\s*\n", text):
        cleaned = " ".join(line.strip(" #\t") for line in paragraph.splitlines()).strip()
        if cleaned and not cleaned.startswith(("<!--", "```")):
            return cleaned[:1024]
    return f"Agent skill instructions for {name}."


def parse_frontmatter(skill_file: Path, allow_legacy: bool = False) -> tuple[str, str, bool]:
    text = skill_file.read_text(encoding="utf-8", errors="replace")
    match = re.match(r"\A---\s*\n(.*?)\n---(?:\s*\n|\Z)", text, re.S)
    if not match:
        if not allow_legacy:
            raise ValueError(f"missing YAML frontmatter: {skill_file}")
        name = re.sub(r"[^a-z0-9-]+", "-", skill_file.parent.name.lower()).strip("-")
        return name, _legacy_description(text, name), True
    frontmatter = match.group(1)
    name = _frontmatter_value(frontmatter, "name")
    description = _frontmatter_value(frontmatter, "description")
    needs_normalization = False
    if not name:
        if not allow_legacy:
            raise ValueError(f"missing 'name' in {skill_file}")
        name = re.sub(r"[^a-z0-9-]+", "-", skill_file.parent.name.lower()).strip("-")
        needs_normalization = True
    if not description:
        if not allow_legacy:
            raise ValueError(f"missing 'description' in {skill_file}")
        description = _legacy_description(text[match.end() :], name)
        needs_normalization = True
    if not re.fullmatch(r"[a-z0-9-]{1,64}", name):
        raise ValueError(f"invalid skill name {name!r}: {skill_file}")
    return name, description, needs_normalization


def walk_skill_files(root: Path) -> Iterable[Path]:
    visited: set[str] = set()
    for dirpath, dirnames, filenames in os.walk(root, followlinks=True):
        real = os.path.realpath(dirpath)
        if real in visited:
            dirnames[:] = []
            continue
        visited.add(real)
        dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDED_DIRS)
        if "SKILL.md" in filenames:
            yield Path(dirpath) / "SKILL.md"


def iter_package_files(skill_dir: Path) -> Iterable[Path]:
    for dirpath, dirnames, filenames in os.walk(skill_dir, followlinks=True):
        current = Path(dirpath)
        kept_dirs: list[str] = []
        for dirname in sorted(dirnames):
            if dirname in EXCLUDED_DIRS:
                continue
            child = current / dirname
            if child != skill_dir and (child / "SKILL.md").is_file():
                continue
            kept_dirs.append(dirname)
        dirnames[:] = kept_dirs
        for filename in sorted(filenames):
            if filename in EXCLUDED_FILES:
                continue
            path = current / filename
            if path.is_file() and path.stat().st_size <= MAX_FILE_BYTES:
                yield path


def package_stats(skill_dir: Path) -> tuple[int, int]:
    count = 0
    total = 0
    for path in iter_package_files(skill_dir):
        try:
            size = path.stat().st_size
        except OSError:
            continue
        count += 1
        total += size
    return count, total


def normalize_remote(remote: str) -> str | None:
    remote = remote.strip()
    if remote.startswith("git@github.com:"):
        remote = "https://github.com/" + remote.removeprefix("git@github.com:")
    if remote.startswith("ssh://git@github.com/"):
        remote = "https://github.com/" + remote.removeprefix("ssh://git@github.com/")
    if remote.endswith(".git"):
        remote = remote[:-4]
    return remote if remote.startswith("https://github.com/") else None


def enclosing_origin(path: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(path), "remote", "get-url", "origin"],
            check=True,
            capture_output=True,
            text=True,
            timeout=3,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return normalize_remote(result.stdout)


def load_claude_sources() -> dict[str, str]:
    lock = HOME / ".claude/skills/skills.lock.json"
    if not lock.is_file():
        return {}
    try:
        data = json.loads(lock.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {
        name: item["source_url"]
        for name, item in data.get("skills", {}).items()
        if isinstance(item, dict) and isinstance(item.get("source_url"), str)
    }


def discover_candidates() -> dict[str, list[SkillCandidate]]:
    claude_sources = load_claude_sources()
    by_name: dict[str, list[SkillCandidate]] = defaultdict(list)
    seen: set[tuple[str, str, str]] = set()
    for label, root in SOURCE_ROOTS:
        if not root.is_dir():
            continue
        for skill_file in walk_skill_files(root):
            try:
                name, description, needs_normalization = parse_frontmatter(skill_file, allow_legacy=True)
                raw = skill_file.read_bytes()
            except (OSError, ValueError) as exc:
                print(f"WARN {exc}", file=sys.stderr)
                continue
            skill_hash = hashlib.sha256(raw).hexdigest()
            real_dir = str(skill_file.parent.resolve())
            identity = (name, label, real_dir)
            if identity in seen:
                continue
            seen.add(identity)
            count, total = package_stats(skill_file.parent)
            origin = claude_sources.get(name) or enclosing_origin(skill_file.parent)
            if label.startswith("Hermes") and not origin:
                origin = "https://github.com/NousResearch/hermes-agent"
            by_name[name].append(
                SkillCandidate(
                    name=name,
                    description=description,
                    source=label,
                    path=skill_file.parent,
                    skill_hash=skill_hash,
                    package_files=count,
                    package_bytes=total,
                    origin_url=origin,
                    needs_normalization=needs_normalization,
                )
            )
    return by_name


def select_candidates(by_name: dict[str, list[SkillCandidate]]) -> dict[str, SkillCandidate]:
    selected: dict[str, SkillCandidate] = {}
    for name, candidates in sorted(by_name.items()):
        groups: dict[str, list[SkillCandidate]] = defaultdict(list)
        for candidate in candidates:
            groups[candidate.skill_hash].append(candidate)
        ranked_groups = sorted(
            groups.values(),
            key=lambda group: max(
                (item.package_files, item.package_bytes, -SOURCE_PRIORITY.get(item.source, 999))
                for item in group
            ),
            reverse=True,
        )
        for group_index, group in enumerate(ranked_groups):
            candidate = max(
                group,
                key=lambda item: (
                    item.package_files,
                    item.package_bytes,
                    -SOURCE_PRIORITY.get(item.source, 999),
                ),
            )
            output_name = name
            if group_index:
                suffix = re.sub(r"[^a-z0-9]+", "-", candidate.source.lower()).strip("-")
                base = name[: max(1, 63 - len(suffix))].rstrip("-")
                output_name = f"{base}-{suffix}"
                serial = 2
                while output_name in selected:
                    serial_suffix = f"-{serial}"
                    output_name = f"{base[:64-len(suffix)-len(serial_suffix)-1]}-{suffix}{serial_suffix}"
                    serial += 1
            selected[output_name] = candidate
    return selected


def is_secret_filename(path: Path) -> bool:
    return any(pattern.fullmatch(path.name) for pattern in SECRET_FILE_PATTERNS)


def scan_publish_safety(name: str, source_dir: Path) -> list[str]:
    findings: list[str] = []
    for path in iter_package_files(source_dir):
        relative = path.relative_to(source_dir)
        if is_secret_filename(path):
            findings.append(f"{name}: sensitive filename {relative}")
            continue
        try:
            size = path.stat().st_size
        except OSError as exc:
            findings.append(f"{name}: unreadable {relative}: {exc}")
            continue
        if size > MAX_FILE_BYTES:
            findings.append(f"{name}: file exceeds 50 MiB: {relative} ({size} bytes)")
            continue
        if size > TEXT_SCAN_BYTES:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        for label, pattern in SECRET_CONTENT_PATTERNS:
            if pattern.search(text):
                findings.append(f"{name}: possible {label} in {relative}")
    return findings


def _normalized_skill_text(text: str, output_name: str, description: str) -> str:
    match = re.match(r"\A---\s*\n(.*?)\n---(?:\s*\n|\Z)", text, re.S)
    if not match:
        return f'---\nname: {output_name}\ndescription: "{description.replace(chr(34), chr(39))}"\n---\n\n{text.lstrip()}'
    frontmatter = match.group(1)
    if re.search(r"^name:\s*.*$", frontmatter, re.M):
        frontmatter = re.sub(r"^name:\s*.*$", f"name: {output_name}", frontmatter, count=1, flags=re.M)
    else:
        frontmatter = f"name: {output_name}\n{frontmatter}"
    if not re.search(r"^description:\s*.*$", frontmatter, re.M):
        safe_description = description.replace('"', "'")
        frontmatter = f'{frontmatter}\ndescription: "{safe_description}"'
    return f"---\n{frontmatter}\n---\n\n{text[match.end():].lstrip()}"


def copy_package(candidate: SkillCandidate, output_name: str, destination: Path) -> None:
    source = candidate.path
    destination.mkdir(parents=True, exist_ok=False)
    for path in iter_package_files(source):
        relative = path.relative_to(source)
        target = destination / relative
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(path, target, follow_symlinks=True)
    skill_file = destination / "SKILL.md"
    text = skill_file.read_text(encoding="utf-8", errors="replace")
    if candidate.needs_normalization or output_name != candidate.name:
        skill_file.write_text(_normalized_skill_text(text, output_name, candidate.description), encoding="utf-8")


def repo_skills() -> dict[str, tuple[Path, str, str]]:
    result: dict[str, tuple[Path, str, str]] = {}
    for skill_file in sorted(REPO_ROOT.glob("*/SKILL.md")):
        name, description, _ = parse_frontmatter(skill_file, allow_legacy=True)
        if name != skill_file.parent.name:
            raise RuntimeError(f"directory/name mismatch: {skill_file.parent.name} != {name}")
        if name in result:
            raise RuntimeError(f"duplicate repository skill name: {name}")
        result[name] = (skill_file.parent, description, hashlib.sha256(skill_file.read_bytes()).hexdigest())
    return result


def normalize_repo_skill_files() -> int:
    normalized = 0
    for skill_file in sorted(REPO_ROOT.glob("*/SKILL.md")):
        name, description, needs_normalization = parse_frontmatter(skill_file, allow_legacy=True)
        output_name = skill_file.parent.name
        if needs_normalization or name != output_name:
            text = skill_file.read_text(encoding="utf-8", errors="replace")
            skill_file.write_text(_normalized_skill_text(text, output_name, description), encoding="utf-8")
            normalized += 1
    return normalized


def agent_spec_validator() -> Path | None:
    candidates = (
        REPO_ROOT / "universal-skills-manager/scripts/validate_frontmatter.py",
        HOME / ".codex/skills/universal-skills-manager/scripts/validate_frontmatter.py",
        HOME / ".claude/skills/universal-skills-manager/scripts/validate_frontmatter.py",
    )
    return next((path for path in candidates if path.is_file()), None)


def normalize_agent_spec_frontmatter() -> int:
    validator = agent_spec_validator()
    if not validator:
        raise RuntimeError("Agent Skills frontmatter validator is unavailable")
    normalized = 0
    for skill_file in sorted(REPO_ROOT.glob("*/SKILL.md")):
        before = hashlib.sha256(skill_file.read_bytes()).digest()
        text = skill_file.read_text(encoding="utf-8", errors="replace")
        text = re.sub(
            r'^metadata:\s*\{\s*"([A-Za-z0-9_.-]+)"\s*:\s*"([^"]*)"\s*\}\s*$',
            lambda match: f'metadata:\n  {match.group(1)}: "{match.group(2)}"',
            text,
            flags=re.M,
        )
        skill_file.write_text(text, encoding="utf-8")
        subprocess.run(
            ["python3", str(validator), str(skill_file), "--fix", "--json"],
            capture_output=True,
            text=True,
        )
        text = skill_file.read_text(encoding="utf-8", errors="replace")
        text = re.sub(r"(?m)^  [A-Za-z0-9_.-]+:\s*$\n", "", text)
        skill_file.write_text(text, encoding="utf-8")
        result = subprocess.run(
            ["python3", str(validator), str(skill_file), "--json"],
            capture_output=True,
            text=True,
        )
        if result.returncode:
            raise RuntimeError(f"frontmatter fix failed for {skill_file}: {result.stdout}{result.stderr}")
        after = hashlib.sha256(skill_file.read_bytes()).digest()
        normalized += before != after
    return normalized


def validate_agent_spec(skill_file: Path) -> list[str]:
    validator = agent_spec_validator()
    if not validator:
        return ["Agent Skills frontmatter validator is unavailable"]
    result = subprocess.run(
        ["python3", str(validator), str(skill_file), "--json"],
        capture_output=True,
        text=True,
    )
    if not result.returncode:
        return []
    try:
        data = json.loads(result.stdout)
    except json.JSONDecodeError:
        return [f"frontmatter validator failed for {skill_file}: {result.stdout}{result.stderr}"]
    issues = data.get("issues") or data.get("errors") or []
    return [f"{skill_file.parent.name}: {issue}" for issue in issues]


def source_summary(
    name: str,
    by_name: dict[str, list[SkillCandidate]],
    selected: dict[str, SkillCandidate],
) -> tuple[list[str], str | None]:
    selected_candidate = selected.get(name)
    if selected_candidate:
        candidates = [
            candidate
            for candidate in by_name.get(selected_candidate.name, [])
            if candidate.skill_hash == selected_candidate.skill_hash
        ]
    else:
        candidates = by_name.get(name, [])
    sources = sorted({candidate.source for candidate in candidates})
    origins = sorted({candidate.origin_url for candidate in candidates if candidate.origin_url})
    return sources, origins[0] if origins else None


def render_skill_readme(name: str, description: str, sources: list[str], origin: str | None, skill_dir: Path) -> str:
    contents: list[str] = []
    for child in sorted(skill_dir.iterdir(), key=lambda item: item.name.lower()):
        if child.name == "README.md":
            continue
        label = f"[{child.name}](./{child.name})" if child.is_file() else f"`{child.name}/`"
        contents.append(f"- {label}")
    source_text = ", ".join(sources) if sources else "Maintained directly in this repository"
    origin_line = f"\n- Upstream: [{origin}]({origin})" if origin else ""
    return f"""{GENERATED_README_MARKER}
# {name}

{description}

## Use

Ask your agent to use `${name}`, or have it read [SKILL.md](./SKILL.md) before starting the task.

## Contents

{chr(10).join(contents)}

## Provenance

- Installed sources: {source_text}{origin_line}
- This catalog excludes local credentials, caches, dependency trees, and VCS metadata.
"""


def write_skill_readmes(
    by_name: dict[str, list[SkillCandidate]],
    selected: dict[str, SkillCandidate],
) -> int:
    written = 0
    for name, (skill_dir, description, _) in repo_skills().items():
        readme = skill_dir / "README.md"
        if readme.is_file() and GENERATED_README_MARKER not in readme.read_text(encoding="utf-8", errors="replace"):
            continue
        sources, origin = source_summary(name, by_name, selected)
        content = render_skill_readme(name, description, sources, origin, skill_dir)
        if not readme.is_file() or readme.read_text(encoding="utf-8") != content:
            readme.write_text(content, encoding="utf-8")
            written += 1
    return written


def render_root_readme(catalog: list[dict[str, object]]) -> str:
    rows = []
    for item in catalog:
        sources = ", ".join(item["sources"]) if item["sources"] else "Repository"
        description = str(item["description"]).replace("|", "\\|").replace("\n", " ")
        rows.append(f"| [{item['name']}](./{item['name']}/) | {sources} | {description} |")
    return f"""# Samin's Agent Skills

A public, deduplicated catalog of agent skills installed across Codex, Claude, Hermes, Gemini, Agents, Cursor, OpenCode, Copilot, and project-level stores.

## Catalog

{len(catalog)} skills are checked into this repository. Every skill has its canonical `SKILL.md` and a human-readable `README.md`.

| Skill | Installed in | Description |
|---|---|---|
{chr(10).join(rows)}

## Synchronization

Run the gauntlet locally:

```bash
python3 scripts/sync_skill_catalog.py
python3 scripts/sync_skill_catalog.py --apply
python3 scripts/sync_skill_catalog.py --check
```

The sync fails closed on potential secrets, missing READMEs, or catalog drift. System skills, plugin caches, dependency trees, credentials, Git metadata, and generated binaries over 50 MiB are excluded.

When two installed skills share a name but have different instructions, the broader installation keeps the base name and the project-specific copy receives a source suffix. Nothing is silently overwritten.

## Licensing and provenance

Imported skills retain their upstream terms. Each generated skill README and `skill-catalog.json` records the detected ecosystem and public upstream URL when available; inclusion here does not relicense third-party work.

## Standalone skills

- [voice-orchestrator](https://github.com/Samin12/voice-orchestrator) is also published as its own repository.
"""


def build_catalog(
    by_name: dict[str, list[SkillCandidate]],
    selected: dict[str, SkillCandidate],
) -> list[dict[str, object]]:
    items: list[dict[str, object]] = []
    for name, (_, description, skill_hash) in sorted(repo_skills().items()):
        sources, origin = source_summary(name, by_name, selected)
        items.append(
            {
                "name": name,
                "description": description,
                "path": name,
                "sources": sources,
                "origin": origin,
                "skill_sha256": skill_hash,
            }
        )
    return items


def write_catalog(
    by_name: dict[str, list[SkillCandidate]],
    selected: dict[str, SkillCandidate],
) -> None:
    catalog = build_catalog(by_name, selected)
    (REPO_ROOT / "skill-catalog.json").write_text(json.dumps(catalog, indent=2) + "\n", encoding="utf-8")
    (REPO_ROOT / "README.md").write_text(render_root_readme(catalog), encoding="utf-8")


def validate(by_name: dict[str, list[SkillCandidate]]) -> list[str]:
    problems: list[str] = []
    skills = repo_skills()
    for name, (skill_dir, _, _) in skills.items():
        try:
            _, _, needs_normalization = parse_frontmatter(skill_dir / "SKILL.md", allow_legacy=True)
        except ValueError as exc:
            problems.append(str(exc))
            continue
        if needs_normalization:
            problems.append(f"legacy frontmatter not normalized: {name}")
        problems.extend(validate_agent_spec(skill_dir / "SKILL.md"))
        if not (skill_dir / "README.md").is_file():
            problems.append(f"missing README: {name}")
    manifest = REPO_ROOT / "skill-catalog.json"
    if not manifest.is_file():
        problems.append("missing skill-catalog.json")
    else:
        try:
            data = json.loads(manifest.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError) as exc:
            problems.append(f"invalid skill-catalog.json: {exc}")
        else:
            manifest_names = [item.get("name") for item in data if isinstance(item, dict)]
            if manifest_names != sorted(skills):
                problems.append("skill-catalog.json does not match repository skills")
    root_readme = REPO_ROOT / "README.md"
    if not root_readme.is_file():
        problems.append("missing root README.md")
    else:
        text = root_readme.read_text(encoding="utf-8", errors="replace")
        for name in skills:
            if f"](./{name}/)" not in text:
                problems.append(f"root README missing catalog link: {name}")
    for name, candidate in select_candidates(by_name).items():
        if name not in skills:
            problems.append(f"installed skill missing from repository: {name}")
    for name, (skill_dir, _, _) in skills.items():
        problems.extend(scan_publish_safety(name, skill_dir))
    return problems


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--apply", action="store_true", help="copy missing skills and regenerate catalog docs")
    mode.add_argument("--check", action="store_true", help="validate the checked-in catalog")
    args = parser.parse_args()

    by_name = discover_candidates()
    selected = select_candidates(by_name)
    existing = repo_skills()
    missing = sorted(set(selected) - set(existing))

    safety_findings: list[str] = []
    for name in missing:
        safety_findings.extend(scan_publish_safety(name, selected[name].path))
    if safety_findings:
        print("PUBLISH SAFETY BLOCKERS", file=sys.stderr)
        for finding in safety_findings:
            print(f"- {finding}", file=sys.stderr)
        return 2

    if args.check:
        problems = validate(by_name)
        if problems:
            print("CATALOG CHECK FAILED")
            for problem in problems:
                print(f"- {problem}")
            return 1
        print(f"CATALOG CHECK PASSED: {len(existing)} skills, all documented and indexed")
        return 0

    total_bytes = sum(selected[name].package_bytes for name in missing)
    print(f"DISCOVERED {len(selected)} unique installed skills from {len(SOURCE_ROOTS)} configured stores")
    print(f"REPOSITORY {len(existing)} skills")
    print(f"MISSING {len(missing)} skills ({total_bytes} source bytes before exclusions)")
    for name in missing:
        candidate = selected[name]
        print(f"+ {name} [{candidate.source}] {candidate.package_files} files {candidate.package_bytes} bytes")

    if not args.apply:
        print("DRY RUN: use --apply to synchronize")
        return 0

    normalized = normalize_repo_skill_files()
    for name in missing:
        copy_package(selected[name], name, REPO_ROOT / name)
    spec_normalized = normalize_agent_spec_frontmatter()
    readmes = write_skill_readmes(by_name, selected)
    write_catalog(by_name, selected)
    problems = validate(by_name)
    if problems:
        print("CATALOG CHECK FAILED AFTER APPLY", file=sys.stderr)
        for problem in problems:
            print(f"- {problem}", file=sys.stderr)
        return 1
    print(
        f"APPLIED {len(missing)} skills; normalized {normalized} legacy skills; "
        f"normalized {spec_normalized} Agent Skills frontmatter blocks; "
        f"wrote or refreshed {readmes} skill READMEs"
    )
    print(f"CATALOG CHECK PASSED: {len(repo_skills())} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
